services:
    sonata.admin.tag:
        class: Application\Sonata\ClassificationBundle\Admin\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Mot-clé" }
        arguments:
            - ~
            - Application\Sonata\ClassificationBundle\Entity\Tag
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]