<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends EntityRepository
{
    public function getReportsWithTags()
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.tags', 'tags')
            ->addSelect('tags')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
